local llm = require('llm')

describe('token count', function()
  it('counts tokens across git files', function()
    local tmp = vim.fn.tempname()
    vim.fn.system({'git', 'init', tmp})
    vim.fn.writefile({'abcd'}, tmp .. '/a.txt')
    vim.fn.writefile({'efgh'}, tmp .. '/b.txt')
    vim.fn.system({'git', '-C', tmp, 'add', '.'})
    local cwd = vim.fn.getcwd()
    vim.fn.chdir(tmp)
    local count = llm.token_count()
    vim.fn.chdir(cwd)
    assert.equals(2, count)
  end)
end)
